/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class target_SerialJNI */

#ifndef _Included_target_SerialJNI
#define _Included_target_SerialJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     target_SerialJNI
 * Method:    open_port
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_target_SerialJNI_open_1port
  (JNIEnv *, jobject, jstring);

/*
 * Class:     target_SerialJNI
 * Method:    write
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_target_SerialJNI_write
  (JNIEnv *, jobject, jchar);

/*
 * Class:     target_SerialJNI
 * Method:    read_char
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_target_SerialJNI_read_1char
  (JNIEnv *, jobject);

/*
 * Class:     target_SerialJNI
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_target_SerialJNI_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
