/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ctrl_Serial_JNI */

#ifndef _Included_ctrl_Serial_JNI
#define _Included_ctrl_Serial_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ctrl_Serial_JNI
 * Method:    open_port
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ctrl_Serial_1JNI_open_1port
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ctrl_Serial_JNI
 * Method:    write
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_ctrl_Serial_1JNI_write
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     ctrl_Serial_JNI
 * Method:    read_char
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_ctrl_Serial_1JNI_read_1char
  (JNIEnv *, jobject, jint);

/*
 * Class:     ctrl_Serial_JNI
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ctrl_Serial_1JNI_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
